title: firedef
email: firedef2019@example.com
description: My personal website
baseurl: ""
url: "https://firedef.github.io"
github_username: firedef
read_time: true
words_per_minute: 200

# Build settings
plugins:
  - jekyll-feed

markdown: kramdown
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"

# Analytics
google_analytics: G-JRVBSZDX88

remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/sass/custom.css"

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Pages defaults
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: simple
      comments: true
      share: true

author:
  name: Dmitrii Nosov
  picture: /images/testImage.png
  email: firedef2019@gmail.com
  links:
    - title: Github
      url: https://github.com/firedef
      icon: fab fa-github


include:
  - _pages